import { useMemo, useRef, useState } from 'react'
import type { Booking } from './types/database'
import { dateRangeBookings, downloadBookingsCsv } from './lib/exports'
import { useModalAccessibility } from './lib/useModalAccessibility'

export function ExportDialog({allBookings,filteredBookings,onClose}:{allBookings:Booking[];filteredBookings:Booking[];onClose:()=>void}){
  const dialogRef=useRef<HTMLElement>(null)
  const startDates=allBookings.map(item=>item.serviceDate).sort(),endDates=allBookings.map(item=>item.serviceEndDate||item.serviceDate).sort(),[startDate,setStartDate]=useState(startDates[0]||''),[endDate,setEndDate]=useState(endDates.at(-1)||''),[error,setError]=useState('')
  const seasonBookings=useMemo(()=>dateRangeBookings(allBookings,startDate,endDate),[allBookings,startDate,endDate])
  const exportFiltered=()=>downloadBookingsCsv(filteredBookings,`goeast-bookings-${new Date().toISOString().slice(0,10)}`)
  const exportSeason=()=>{if(!startDate||!endDate){setError('Select both a start and end date.');return}if(startDate>endDate){setError('The end date must be on or after the start date.');return}setError('');downloadBookingsCsv(seasonBookings,`goeast-season-${startDate}-to-${endDate}`)}
  useModalAccessibility(dialogRef,onClose)
  return <div className="export-modal-scrim" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section ref={dialogRef} className="export-modal" role="dialog" aria-modal="true" aria-labelledby="export-title"><header><div><p className="eyebrow">DOWNLOAD</p><h2 id="export-title">Export bookings</h2><p>CSV files open directly in Excel, Numbers, and Google Sheets.</p></div><button onClick={onClose} aria-label="Close export dialog" autoFocus>×</button></header><div className="export-options"><article><div><span className="export-option-number">01</span><div><h3>Current filtered view</h3><p>Exports exactly the bookings currently shown in the Bookings table.</p></div></div><strong>{filteredBookings.length} booking{filteredBookings.length===1?'':'s'}</strong><button className="secondary-button" onClick={exportFiltered} disabled={!filteredBookings.length}>Download filtered CSV</button></article><article><div><span className="export-option-number">02</span><div><h3>Season or date range</h3><p>Exports all bookings whose service date falls within this range.</p></div></div><div className="export-date-range"><label><span>Start date</span><input type="date" value={startDate} onChange={event=>{setStartDate(event.target.value);setError('')}}/></label><label><span>End date</span><input type="date" value={endDate} onChange={event=>{setEndDate(event.target.value);setError('')}}/></label></div>{error&&<div className="export-error" role="alert">{error}</div>}<div className="export-season-footer"><strong>{seasonBookings.length} booking{seasonBookings.length===1?'':'s'}</strong><button className="primary-button" onClick={exportSeason} disabled={!seasonBookings.length}>Download season CSV</button></div></article></div></section></div>
}
