import { useMemo, useRef, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { createCustomer, deleteCustomer, getCustomerBookingCount, updateCustomer } from './services/customers'
import { createCruiseLine, deleteResource, getResourceUsage, saveShip, saveStaff, saveTour, saveVehicle, setStaffActive, setTourActive, setVehicleActive, updateCruiseLine } from './services/resources'
import type { DeletableResource } from './services/resources'
import type { Booking, CruiseLineRow, CustomerRow, ResourceOptions, ShipRow, StaffRow, TourRow, VehicleRow } from './types/database'
import { useConfirmation } from './components/confirmationContext'
import type { ConfirmationRequest } from './components/confirmationContext'
import { useModalAccessibility } from './lib/useModalAccessibility'
import { clearFormDraft, formDraftKey, useDraftDiscard, useFormDraft } from './lib/useFormDraft'
import { formatDuration } from './lib/schedule'

type Refresh = () => Promise<void>
type Feedback = {kind:'success'|'error';message:string}|null

function PageHeader({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:ReactNode}){
  return <header className="resource-page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div><div className="resource-header-actions">{children}</div></header>
}
function Search({value,onChange,placeholder}:{value:string;onChange:(value:string)=>void;placeholder:string}){
  return <label className="resource-search"><span aria-hidden="true">⌕</span><input type="search" value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder}/></label>
}
function FeedbackBanner({feedback}:{feedback:Feedback}){return feedback?<div className={`resource-feedback ${feedback.kind}`} role="status">{feedback.kind==='success'?'✓':'!'} {feedback.message}</div>:null}
function ActiveBadge({active}:{active:boolean}){return <span className={`active-badge ${active?'is-active':'is-inactive'}`}><i/>{active?'Active':'Inactive'}</span>}
function Empty({label}:{label:string}){return <div className="resource-empty"><strong>No {label} found</strong><span>Try another search or create a new record.</span></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
  const dialogRef=useRef<HTMLElement>(null)
  useModalAccessibility(dialogRef,onClose)
  return <div className="resource-modal-scrim" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><section ref={dialogRef} className="resource-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><p className="eyebrow">RESOURCE RECORD</p><h2>{title}</h2></div><button type="button" className="modal-close" onClick={onClose} aria-label="Close">×</button></header>{children}</section></div>
}
function FormActions({saving,onCancel}:{saving:boolean;onCancel:()=>void}){return <div className="resource-form-actions"><button type="button" className="secondary-button" onClick={onCancel} disabled={saving}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving…':'Save'}</button></div>}
function Field({label,children,wide=false}:{label:string;children:ReactNode;wide?:boolean}){return <label className={`resource-field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}
function Actions({children}:{children:ReactNode}){return <div className="resource-row-actions">{children}</div>}
async function requestResourceDeletion(resource:DeletableResource,id:string,name:string,onRefresh:Refresh,setSaving:(value:boolean)=>void,setFeedback:(value:Feedback)=>void,setConfirmation:(value:ConfirmationRequest)=>void){
  setSaving(true);setFeedback(null)
  try{
    const usage=await getResourceUsage(resource,id)
    if(usage.count){setFeedback({kind:'error',message:usage.message});return}
    setConfirmation({title:`Delete ${name}?`,message:`This action permanently deletes ${name} and cannot be undone.`,cancelLabel:'Keep record',confirmLabel:'Delete permanently',destructive:true,onConfirm:async()=>{try{await deleteResource(resource,id);clearFormDraft(formDraftKey(resource,id));await onRefresh();setFeedback({kind:'success',message:`${name} deleted successfully.`})}catch(error){throw new Error(errorMessage(error))}}})
  }catch(error){setFeedback({kind:'error',message:errorMessage(error)})}finally{setSaving(false)}
}

export function ToursPage({items,onRefresh}:{items:TourRow[];onRefresh:Refresh}){
  const confirm=useConfirmation()
  const [query,setQuery]=useState(''),[editing,setEditing]=useState<TourRow|null|undefined>(),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState<Feedback>(null)
  const filtered=items.filter(item=>item.name.toLowerCase().includes(query.toLowerCase()))
  const changeActive=async(item:TourRow)=>{setSaving(true);setFeedback(null);try{await setTourActive(item.id,!item.active);await onRefresh();setFeedback({kind:'success',message:`${item.name} is now ${item.active?'inactive':'active'}.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}
  const toggle=(item:TourRow)=>{if(!item.active){void changeActive(item).catch(()=>undefined);return}confirm({title:'Deactivate tour?',message:`${item.name} will no longer be available for new bookings. Existing bookings remain unchanged.`,cancelLabel:'Keep active',confirmLabel:'Deactivate',destructive:true,onConfirm:()=>changeActive(item)})}
  const remove=(item:TourRow)=>requestResourceDeletion('tour',item.id,item.name,onRefresh,setSaving,setFeedback,confirm)
  return <div className="page resource-page"><PageHeader eyebrow="RESOURCES" title="Tours" description="Manage bookable experiences and their default operating duration."><button className="primary-button" onClick={()=>setEditing(null)}>+ New tour</button></PageHeader><FeedbackBanner feedback={feedback}/><section className="panel resource-panel"><div className="resource-toolbar"><Search value={query} onChange={setQuery} placeholder="Search tours…"/><span>{filtered.length} tours</span></div>{filtered.length?<><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>NAME</th><th>DEFAULT DURATION</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{formatDuration(item.default_duration_minutes)}</td><td><ActiveBadge active={item.active}/></td><td><Actions><button onClick={()=>setEditing(item)}>Edit</button><button disabled={saving} onClick={()=>void toggle(item)}>{item.active?'Deactivate':'Activate'}</button><button className="resource-delete" disabled={saving} onClick={()=>void remove(item)}>Delete</button></Actions></td></tr>)}</tbody></table></div><div className="resource-mobile-list">{filtered.map(item=><article className="resource-mobile-card" key={item.id}><div><strong>{item.name}</strong><ActiveBadge active={item.active}/></div><dl><dt>Default duration</dt><dd>{formatDuration(item.default_duration_minutes)}</dd></dl><Actions><button onClick={()=>setEditing(item)}>Edit</button><button disabled={saving} onClick={()=>void toggle(item)}>{item.active?'Deactivate':'Activate'}</button><button className="resource-delete" disabled={saving} onClick={()=>void remove(item)}>Delete</button></Actions></article>)}</div></>:<Empty label="tours"/>}</section>{editing!==undefined&&<TourForm item={editing} saving={saving} onClose={()=>setEditing(undefined)} onSave={async input=>{setSaving(true);setFeedback(null);try{await saveTour(input);await onRefresh();setEditing(undefined);setFeedback({kind:'success',message:`Tour ${input.id?'updated':'created'} successfully.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}}/>}</div>
}
function TourForm({item,saving,onClose,onSave}:{item:TourRow|null;saving:boolean;onClose:()=>void;onSave:(input:{id?:string;name:string;default_duration_minutes:number|null;active:boolean})=>Promise<void>}){
  const total=item?.default_duration_minutes,initial={name:item?.name||'',hours:total==null?'':String(Math.floor(total/60)),minutes:total==null?'':String(total%60),active:item?.active??true}
  const {value:form,setValue:setForm,dirty,clearDraft}=useFormDraft(formDraftKey('tour',item?.id),initial,item?`tour-duration-v2:${JSON.stringify(item)}`:'new-tour-v2')
  const discard=useDraftDiscard(dirty,clearDraft,onClose,'tour')
  const [durationError,setDurationError]=useState('')
  const set=<K extends keyof typeof form>(key:K,value:(typeof form)[K])=>setForm(current=>({...current,[key]:value}))
  const setDuration=(key:'hours'|'minutes',value:string)=>{set(key,value);setDurationError('')}
  const submit=async(event:FormEvent)=>{event.preventDefault();if(saving||!form.name.trim())return;const provided=form.hours!==''||form.minutes!=='',hours=form.hours===''?0:Number(form.hours),minutes=form.minutes===''?0:Number(form.minutes),duration=hours*60+minutes;if(!Number.isInteger(hours)||hours<0){setDurationError('Hours must be a whole number of zero or more.');return}if(!Number.isInteger(minutes)||minutes<0||minutes>59){setDurationError('Minutes must be a whole number between 0 and 59.');return}if(provided&&duration<=0){setDurationError('Total duration must be greater than zero.');return}try{await onSave({id:item?.id,name:form.name.trim(),default_duration_minutes:provided?duration:null,active:form.active});clearDraft()}catch{ /* Parent displays the save error. */ }}
  return <Modal title={item?'Edit tour':'New tour'} onClose={discard}><form className="resource-form" onSubmit={event=>void submit(event)}><div className="resource-form-grid"><Field label="Tour name" wide><input value={form.name} onChange={event=>set('name',event.target.value)} required/></Field><div className="duration-fields"><Field label="Hours"><input type="number" inputMode="numeric" min="0" step="1" value={form.hours} onChange={event=>setDuration('hours',event.target.value)} placeholder="0"/></Field><Field label="Minutes"><input type="number" inputMode="numeric" min="0" max="59" step="1" value={form.minutes} onChange={event=>setDuration('minutes',event.target.value)} placeholder="0"/></Field>{durationError&&<em className="duration-error" role="alert">{durationError}</em>}</div><label className="resource-toggle"><input type="checkbox" checked={form.active} onChange={event=>set('active',event.target.checked)}/><span>Active and available for new bookings</span></label></div><FormActions saving={saving} onCancel={discard}/></form></Modal>
}

export function ShipsPage({ships,resources,onRefresh}:{ships:ShipRow[];resources:ResourceOptions;onRefresh:Refresh}){
  const confirm=useConfirmation()
  const [query,setQuery]=useState(''),[editing,setEditing]=useState<ShipRow|null|undefined>(),[editingLine,setEditingLine]=useState<CruiseLineRow|null|undefined>(),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState<Feedback>(null)
  const lineName=(id:string|null)=>resources.cruiseLines.find(line=>line.id===id)?.name||'Unassigned'
  const filtered=ships.filter(ship=>`${ship.name} ${lineName(ship.cruise_line_id)}`.toLowerCase().includes(query.toLowerCase()))
  const removeShip=(item:ShipRow)=>requestResourceDeletion('ship',item.id,item.name,onRefresh,setSaving,setFeedback,confirm)
  const removeLine=(item:CruiseLineRow)=>requestResourceDeletion('cruiseLine',item.id,item.name,onRefresh,setSaving,setFeedback,confirm)
  const saveLine=async(input:{id?:string;name:string})=>{setSaving(true);setFeedback(null);try{if(input.id)await updateCruiseLine(input.id,input.name);else await createCruiseLine(input.name);await onRefresh();setEditingLine(undefined);setFeedback({kind:'success',message:`Cruise line ${input.id?'updated':'created'} successfully.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}
  return <div className="page resource-page">
    <PageHeader eyebrow="RESOURCES" title="Ships" description="Maintain cruise ships and the cruise lines they operate under."><button className="secondary-button" onClick={()=>setEditingLine(null)}>New cruise line</button><button className="primary-button" onClick={()=>setEditing(null)}>+ New ship</button></PageHeader>
    <FeedbackBanner feedback={feedback}/>
    <section className="panel resource-panel"><div className="resource-toolbar"><Search value={query} onChange={setQuery} placeholder="Search ships or cruise lines…"/><span>{filtered.length} ships</span></div>{filtered.length?<><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>SHIP NAME</th><th>CRUISE LINE</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{lineName(item.cruise_line_id)}</td><td><Actions><button onClick={()=>setEditing(item)}>Edit</button><button className="resource-delete" disabled={saving} onClick={()=>void removeShip(item)}>Delete</button></Actions></td></tr>)}</tbody></table></div><div className="resource-mobile-list">{filtered.map(item=><article className="resource-mobile-card" key={item.id}><div><strong>{item.name}</strong></div><dl><dt>Cruise line</dt><dd>{lineName(item.cruise_line_id)}</dd></dl><Actions><button onClick={()=>setEditing(item)}>Edit</button><button className="resource-delete" disabled={saving} onClick={()=>void removeShip(item)}>Delete</button></Actions></article>)}</div></>:<Empty label="ships"/>}</section>
    <section className="panel resource-panel cruise-lines-panel"><div className="resource-toolbar"><strong>Cruise lines</strong><span>{resources.cruiseLines.length} cruise lines</span></div>{resources.cruiseLines.length?<><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>CRUISE LINE</th><th>SHIPS</th><th>ACTIONS</th></tr></thead><tbody>{resources.cruiseLines.map(line=><tr key={line.id}><td><strong>{line.name}</strong></td><td>{ships.filter(ship=>ship.cruise_line_id===line.id).length}</td><td><Actions><button onClick={()=>setEditingLine(line)}>Edit</button><button className="resource-delete" disabled={saving} onClick={()=>void removeLine(line)}>Delete</button></Actions></td></tr>)}</tbody></table></div><div className="resource-mobile-list">{resources.cruiseLines.map(line=><article className="resource-mobile-card" key={line.id}><div><strong>{line.name}</strong></div><dl><dt>Ships</dt><dd>{ships.filter(ship=>ship.cruise_line_id===line.id).length}</dd></dl><Actions><button onClick={()=>setEditingLine(line)}>Edit</button><button className="resource-delete" disabled={saving} onClick={()=>void removeLine(line)}>Delete</button></Actions></article>)}</div></>:<Empty label="cruise lines"/>}</section>
    {editing!==undefined&&<ShipForm item={editing} lines={resources.cruiseLines} saving={saving} onClose={()=>setEditing(undefined)} onSave={async input=>{setSaving(true);setFeedback(null);try{await saveShip(input);await onRefresh();setEditing(undefined);setFeedback({kind:'success',message:`Ship ${input.id?'updated':'created'} successfully.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}}/>}
    {editingLine!==undefined&&<CruiseLineForm item={editingLine} saving={saving} onClose={()=>setEditingLine(undefined)} onSave={saveLine}/>}
  </div>
}
function ShipForm({item,lines,saving,onClose,onSave}:{item:ShipRow|null;lines:ResourceOptions['cruiseLines'];saving:boolean;onClose:()=>void;onSave:(input:{id?:string;name:string;cruise_line_id:string})=>Promise<void>}){
  const initial={name:item?.name||'',lineId:item?.cruise_line_id||lines[0]?.id||''}
  const {value:form,setValue:setForm,dirty,clearDraft}=useFormDraft(formDraftKey('ship',item?.id),initial,item?JSON.stringify(item):'new-ship-v1')
  const discard=useDraftDiscard(dirty,clearDraft,onClose,'ship')
  const submit=async(event:FormEvent)=>{event.preventDefault();if(saving||!form.name.trim()||!form.lineId)return;try{await onSave({id:item?.id,name:form.name.trim(),cruise_line_id:form.lineId});clearDraft()}catch{ /* Parent displays the save error. */ }}
  return <Modal title={item?'Edit ship':'New ship'} onClose={discard}><form className="resource-form" onSubmit={event=>void submit(event)}><div className="resource-form-grid"><Field label="Ship name"><input value={form.name} onChange={event=>setForm(current=>({...current,name:event.target.value}))} required/></Field><Field label="Cruise line"><select value={form.lineId} onChange={event=>setForm(current=>({...current,lineId:event.target.value}))} required><option value="">Select a cruise line</option>{lines.map(line=><option key={line.id} value={line.id}>{line.name}</option>)}</select></Field></div><FormActions saving={saving} onCancel={discard}/></form></Modal>
}
function CruiseLineForm({item,saving,onClose,onSave}:{item:CruiseLineRow|null;saving:boolean;onClose:()=>void;onSave:(input:{id?:string;name:string})=>Promise<void>}){
  const initial={name:item?.name||''}
  const {value:form,setValue:setForm,dirty,clearDraft}=useFormDraft(formDraftKey('cruiseLine',item?.id),initial,item?JSON.stringify(item):'new-cruise-line-v1')
  const discard=useDraftDiscard(dirty,clearDraft,onClose,'cruise line')
  const submit=async(event:FormEvent)=>{event.preventDefault();if(saving||!form.name.trim())return;try{await onSave({id:item?.id,name:form.name.trim()});clearDraft()}catch{ /* Parent displays the save error. */ }}
  return <Modal title={item?'Edit cruise line':'New cruise line'} onClose={discard}><form className="resource-form" onSubmit={event=>void submit(event)}><div className="resource-form-grid"><Field label="Cruise line name"><input value={form.name} onChange={event=>setForm({name:event.target.value})} required/></Field></div><FormActions saving={saving} onCancel={discard}/></form></Modal>
}

export function VehiclesPage({items,onRefresh}:{items:VehicleRow[];onRefresh:Refresh}){
  const confirm=useConfirmation()
  const [query,setQuery]=useState(''),[editing,setEditing]=useState<VehicleRow|null|undefined>(),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState<Feedback>(null)
  const filtered=items.filter(item=>`${item.name} ${item.registration_number||''} ${item.notes||''}`.toLowerCase().includes(query.toLowerCase()))
  const changeActive=async(item:VehicleRow)=>{setSaving(true);setFeedback(null);try{await setVehicleActive(item.id,!item.active);await onRefresh();setFeedback({kind:'success',message:`${item.name} is now ${item.active?'inactive':'active'}.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}
  const toggle=(item:VehicleRow)=>{if(!item.active){void changeActive(item).catch(()=>undefined);return}confirm({title:'Deactivate vehicle?',message:`${item.name} will no longer be available for new assignments. Existing bookings remain unchanged.`,cancelLabel:'Keep active',confirmLabel:'Deactivate',destructive:true,onConfirm:()=>changeActive(item)})}
  const remove=(item:VehicleRow)=>requestResourceDeletion('vehicle',item.id,item.name,onRefresh,setSaving,setFeedback,confirm)
  return <div className="page resource-page"><PageHeader eyebrow="RESOURCES" title="Vehicles" description="Manage fleet availability, capacity and operating notes."><button className="primary-button" onClick={()=>setEditing(null)}>+ New vehicle</button></PageHeader><FeedbackBanner feedback={feedback}/><section className="panel resource-panel"><div className="resource-toolbar"><Search value={query} onChange={setQuery} placeholder="Search vehicles…"/><span>{filtered.length} vehicles</span></div>{filtered.length?<><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>VEHICLE</th><th>REGISTRATION</th><th>CAPACITY</th><th>STATUS</th><th>NOTES</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.registration_number||'—'}</td><td>{item.capacity??'—'}</td><td><ActiveBadge active={item.active}/></td><td className="resource-notes-cell">{item.notes||'—'}</td><td><Actions><button onClick={()=>setEditing(item)}>Edit</button><button disabled={saving} onClick={()=>void toggle(item)}>{item.active?'Deactivate':'Activate'}</button><button className="resource-delete" disabled={saving} onClick={()=>void remove(item)}>Delete</button></Actions></td></tr>)}</tbody></table></div><div className="resource-mobile-list">{filtered.map(item=><article className="resource-mobile-card" key={item.id}><div><strong>{item.name}</strong><ActiveBadge active={item.active}/></div><dl><dt>Registration</dt><dd>{item.registration_number||'—'}</dd><dt>Capacity</dt><dd>{item.capacity??'—'}</dd><dt>Notes</dt><dd>{item.notes||'—'}</dd></dl><Actions><button onClick={()=>setEditing(item)}>Edit</button><button disabled={saving} onClick={()=>void toggle(item)}>{item.active?'Deactivate':'Activate'}</button><button className="resource-delete" disabled={saving} onClick={()=>void remove(item)}>Delete</button></Actions></article>)}</div></>:<Empty label="vehicles"/>}</section>{editing!==undefined&&<VehicleForm item={editing} saving={saving} onClose={()=>setEditing(undefined)} onSave={async input=>{setSaving(true);setFeedback(null);try{await saveVehicle(input);await onRefresh();setEditing(undefined);setFeedback({kind:'success',message:`Vehicle ${input.id?'updated':'created'} successfully.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}}/>}</div>
}
function VehicleForm({item,saving,onClose,onSave}:{item:VehicleRow|null;saving:boolean;onClose:()=>void;onSave:(input:{id?:string;name:string;registration_number:string;capacity:number|null;active:boolean;notes:string})=>Promise<void>}){
  const initial={name:item?.name||'',registration:item?.registration_number||'',capacity:item?.capacity?.toString()||'',notes:item?.notes||'',active:item?.active??true}
  const {value:form,setValue:setForm,dirty,clearDraft}=useFormDraft(formDraftKey('vehicle',item?.id),initial,item?JSON.stringify(item):'new-vehicle-v1')
  const discard=useDraftDiscard(dirty,clearDraft,onClose,'vehicle')
  const set=<K extends keyof typeof form>(key:K,value:(typeof form)[K])=>setForm(current=>({...current,[key]:value}))
  const submit=async(event:FormEvent)=>{event.preventDefault();if(saving||!form.name.trim())return;try{await onSave({id:item?.id,name:form.name.trim(),registration_number:form.registration.trim(),capacity:form.capacity===''?null:Number(form.capacity),active:form.active,notes:form.notes.trim()});clearDraft()}catch{ /* Parent displays the save error. */ }}
  return <Modal title={item?'Edit vehicle':'New vehicle'} onClose={discard}><form className="resource-form" onSubmit={event=>void submit(event)}><div className="resource-form-grid"><Field label="Vehicle name"><input value={form.name} onChange={event=>set('name',event.target.value)} required/></Field><Field label="Registration number"><input value={form.registration} onChange={event=>set('registration',event.target.value)}/></Field><Field label="Capacity"><input type="number" min="1" step="1" value={form.capacity} onChange={event=>set('capacity',event.target.value)}/></Field><Field label="Notes" wide><textarea value={form.notes} onChange={event=>set('notes',event.target.value)}/></Field><label className="resource-toggle"><input type="checkbox" checked={form.active} onChange={event=>set('active',event.target.checked)}/><span>Active and available for new bookings</span></label></div><FormActions saving={saving} onCancel={discard}/></form></Modal>
}

export function StaffPage({items,onRefresh}:{items:StaffRow[];onRefresh:Refresh}){
  const confirm=useConfirmation()
  const [query,setQuery]=useState(''),[editing,setEditing]=useState<StaffRow|null|undefined>(),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState<Feedback>(null)
  const filtered=items.filter(item=>`${item.name} ${item.phone||''} ${item.email||''}`.toLowerCase().includes(query.toLowerCase()))
  const changeActive=async(item:StaffRow)=>{setSaving(true);setFeedback(null);try{await setStaffActive(item.id,!item.active);await onRefresh();setFeedback({kind:'success',message:`${item.name} is now ${item.active?'inactive':'active'}.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}
  const toggle=(item:StaffRow)=>{if(!item.active){void changeActive(item).catch(()=>undefined);return}confirm({title:'Deactivate staff member?',message:`${item.name} will no longer be available for new driver or guide assignments. Existing bookings remain unchanged.`,cancelLabel:'Keep active',confirmLabel:'Deactivate',destructive:true,onConfirm:()=>changeActive(item)})}
  const remove=(item:StaffRow)=>requestResourceDeletion('staff',item.id,item.name,onRefresh,setSaving,setFeedback,confirm)
  return <div className="page resource-page"><PageHeader eyebrow="RESOURCES" title="Staff" description="Manage drivers, guides and team availability."><button className="primary-button" onClick={()=>setEditing(null)}>+ New staff member</button></PageHeader><FeedbackBanner feedback={feedback}/><section className="panel resource-panel"><div className="resource-toolbar"><Search value={query} onChange={setQuery} placeholder="Search staff…"/><span>{filtered.length} staff</span></div>{filtered.length?<><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>NAME</th><th>PHONE</th><th>EMAIL</th><th>CAPABILITIES</th><th>STATUS</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.phone||'—'}</td><td>{item.email||'—'}</td><td><Capability staff={item}/></td><td><ActiveBadge active={item.active}/></td><td><Actions><button onClick={()=>setEditing(item)}>Edit</button><button disabled={saving} onClick={()=>void toggle(item)}>{item.active?'Deactivate':'Activate'}</button><button className="resource-delete" disabled={saving} onClick={()=>void remove(item)}>Delete</button></Actions></td></tr>)}</tbody></table></div><div className="resource-mobile-list">{filtered.map(item=><article className="resource-mobile-card" key={item.id}><div><strong>{item.name}</strong><ActiveBadge active={item.active}/></div><Capability staff={item}/><dl><dt>Phone</dt><dd>{item.phone||'—'}</dd><dt>Email</dt><dd>{item.email||'—'}</dd></dl><Actions><button onClick={()=>setEditing(item)}>Edit</button><button disabled={saving} onClick={()=>void toggle(item)}>{item.active?'Deactivate':'Activate'}</button><button className="resource-delete" disabled={saving} onClick={()=>void remove(item)}>Delete</button></Actions></article>)}</div></>:<Empty label="staff members"/>}</section>{editing!==undefined&&<StaffForm item={editing} saving={saving} onClose={()=>setEditing(undefined)} onSave={async input=>{setSaving(true);setFeedback(null);try{await saveStaff(input);await onRefresh();setEditing(undefined);setFeedback({kind:'success',message:`Staff member ${input.id?'updated':'created'} successfully.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}}/>}</div>
}
function Capability({staff}:{staff:StaffRow}){const label=staff.can_drive&&staff.can_guide?'Driver + Guide':staff.can_drive?'Driver':staff.can_guide?'Guide':'No capabilities';return <span className={`capability-badge ${!staff.can_drive&&!staff.can_guide?'empty':''}`}>{label}</span>}
function StaffForm({item,saving,onClose,onSave}:{item:StaffRow|null;saving:boolean;onClose:()=>void;onSave:(input:{id?:string;name:string;phone:string;email:string;can_drive:boolean;can_guide:boolean;active:boolean})=>Promise<void>}){
  const initial={name:item?.name||'',phone:item?.phone||'',email:item?.email||'',canDrive:item?.can_drive??false,canGuide:item?.can_guide??false,active:item?.active??true}
  const {value:form,setValue:setForm,dirty,clearDraft}=useFormDraft(formDraftKey('staff',item?.id),initial,item?JSON.stringify(item):'new-staff-v1')
  const discard=useDraftDiscard(dirty,clearDraft,onClose,'staff member')
  const [capabilityError,setCapabilityError]=useState('')
  const set=<K extends keyof typeof form>(key:K,value:(typeof form)[K])=>setForm(current=>({...current,[key]:value}))
  const submit=async(event:FormEvent)=>{event.preventDefault();if(saving||!form.name.trim())return;if(!form.canDrive&&!form.canGuide){setCapabilityError('Select Driver, Guide, or both.');return}setCapabilityError('');try{await onSave({id:item?.id,name:form.name.trim(),phone:form.phone.trim(),email:form.email.trim(),can_drive:form.canDrive,can_guide:form.canGuide,active:form.active});clearDraft()}catch{ /* Parent displays the save error. */ }}
  return <Modal title={item?'Edit staff member':'New staff member'} onClose={discard}><form className="resource-form" onSubmit={event=>void submit(event)}><div className="resource-form-grid"><Field label="Name"><input value={form.name} onChange={event=>set('name',event.target.value)} required/></Field><Field label="Phone"><input value={form.phone} onChange={event=>set('phone',event.target.value)}/></Field><Field label="Email"><input type="email" value={form.email} onChange={event=>set('email',event.target.value)}/></Field><div className="resource-checks"><label><input type="checkbox" checked={form.canDrive} onChange={event=>{set('canDrive',event.target.checked);setCapabilityError('')}}/> Driver</label><label><input type="checkbox" checked={form.canGuide} onChange={event=>{set('canGuide',event.target.checked);setCapabilityError('')}}/> Guide</label>{capabilityError&&<em>{capabilityError}</em>}</div><label className="resource-toggle"><input type="checkbox" checked={form.active} onChange={event=>set('active',event.target.checked)}/><span>Active and available for new bookings</span></label></div><FormActions saving={saving} onCancel={discard}/></form></Modal>
}

export function CustomersPage({items,onRefresh}:{items:CustomerRow[];onRefresh:Refresh}){
  const confirm=useConfirmation()
  const navigate=useNavigate(),[query,setQuery]=useState(''),[editing,setEditing]=useState<CustomerRow|null|undefined>(),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState<Feedback>(null)
  const filtered=items.filter(item=>`${item.name} ${item.contact_person||''} ${item.email||''} ${item.phone||''}`.toLowerCase().includes(query.toLowerCase()))
  const openCustomer=(id:string)=>navigate(`/customers/${id}`)
  const remove=async(event:React.MouseEvent,item:CustomerRow)=>{event.stopPropagation();setSaving(true);setFeedback(null);try{const count=await getCustomerBookingCount(item.id);if(count){setFeedback({kind:'error',message:`This customer is used by ${count} booking${count===1?'':'s'} and cannot be deleted.`});return}confirm({title:`Delete ${item.name}?`,message:`This action permanently deletes ${item.name} and cannot be undone.`,cancelLabel:'Keep customer',confirmLabel:'Delete permanently',destructive:true,onConfirm:async()=>{try{await deleteCustomer(item.id);clearFormDraft(formDraftKey('customer',item.id));await onRefresh();setFeedback({kind:'success',message:`${item.name} deleted successfully.`})}catch(error){throw new Error(errorMessage(error))}}})}catch(error){setFeedback({kind:'error',message:errorMessage(error)})}finally{setSaving(false)}}
  return <div className="page resource-page"><PageHeader eyebrow="RESOURCES" title="Customers" description="Manage customer and company contact records."><button className="primary-button" onClick={()=>setEditing(null)}>+ New customer</button></PageHeader><FeedbackBanner feedback={feedback}/><section className="panel resource-panel"><div className="resource-toolbar"><Search value={query} onChange={setQuery} placeholder="Search customers…"/><span>{filtered.length} customers</span></div>{filtered.length?<><div className="resource-table-wrap"><table className="resource-table"><thead><tr><th>COMPANY / CUSTOMER</th><th>CONTACT PERSON</th><th>EMAIL</th><th>PHONE</th><th>ACTIONS</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} className="resource-clickable" onClick={()=>openCustomer(item.id)} tabIndex={0} onKeyDown={event=>{if(event.currentTarget===event.target&&(event.key==='Enter'||event.key===' '))openCustomer(item.id)}}><td><strong>{item.name}</strong></td><td>{item.contact_person||'—'}</td><td>{item.email||'—'}</td><td>{item.phone||'—'}</td><td><Actions><button onClick={event=>{event.stopPropagation();openCustomer(item.id)}}>View</button><button onClick={event=>{event.stopPropagation();setEditing(item)}}>Edit</button><button className="resource-delete" disabled={saving} onClick={event=>void remove(event,item)}>Delete</button></Actions></td></tr>)}</tbody></table></div><div className="resource-mobile-list">{filtered.map(item=><article className="resource-mobile-card resource-clickable" key={item.id} onClick={()=>openCustomer(item.id)} tabIndex={0} onKeyDown={event=>{if(event.currentTarget===event.target&&(event.key==='Enter'||event.key===' '))openCustomer(item.id)}}><div><strong>{item.name}</strong></div><dl><dt>Contact</dt><dd>{item.contact_person||'—'}</dd><dt>Email</dt><dd>{item.email||'—'}</dd><dt>Phone</dt><dd>{item.phone||'—'}</dd></dl><Actions><button onClick={event=>{event.stopPropagation();openCustomer(item.id)}}>View</button><button onClick={event=>{event.stopPropagation();setEditing(item)}}>Edit</button><button className="resource-delete" disabled={saving} onClick={event=>void remove(event,item)}>Delete</button></Actions></article>)}</div></>:<Empty label="customers"/>}</section>{editing!==undefined&&<CustomerForm item={editing} saving={saving} onClose={()=>setEditing(undefined)} onSave={async input=>{setSaving(true);setFeedback(null);try{if(input.id)await updateCustomer(input.id,input);else await createCustomer(input);await onRefresh();setEditing(undefined);setFeedback({kind:'success',message:`Customer ${input.id?'updated':'created'} successfully.`})}catch(error){setFeedback({kind:'error',message:errorMessage(error)});throw error}finally{setSaving(false)}}}/>}</div>
}
type CustomerInput={id?:string;name:string;contactPerson:string;email:string;phone:string}
function CustomerForm({item,saving,onClose,onSave}:{item:CustomerRow|null;saving:boolean;onClose:()=>void;onSave:(input:CustomerInput)=>Promise<void>}){
  const initial={name:item?.name||'',contactPerson:item?.contact_person||'',email:item?.email||'',phone:item?.phone||''}
  const {value:form,setValue:setForm,dirty,clearDraft}=useFormDraft(formDraftKey('customer',item?.id),initial,item?JSON.stringify(item):'new-customer-v1')
  const discard=useDraftDiscard(dirty,clearDraft,onClose,'customer')
  const set=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}))
  const submit=async(event:FormEvent)=>{event.preventDefault();if(saving||!form.name.trim())return;try{await onSave({id:item?.id,name:form.name.trim(),contactPerson:form.contactPerson.trim(),email:form.email.trim(),phone:form.phone.trim()});clearDraft()}catch{ /* Parent displays the save error. */ }}
  return <Modal title={item?'Edit customer':'New customer'} onClose={discard}><form className="resource-form" onSubmit={event=>void submit(event)}><div className="resource-form-grid"><Field label="Company / customer name"><input value={form.name} onChange={event=>set('name',event.target.value)} required/></Field><Field label="Contact person"><input value={form.contactPerson} onChange={event=>set('contactPerson',event.target.value)}/></Field><Field label="Email"><input type="email" value={form.email} onChange={event=>set('email',event.target.value)}/></Field><Field label="Phone"><input value={form.phone} onChange={event=>set('phone',event.target.value)}/></Field></div><FormActions saving={saving} onCancel={discard}/></form></Modal>
}

export function CustomerDetailPage({customers,bookings}:{customers:CustomerRow[];bookings:Booking[]}){
  const {customerId}=useParams(),navigate=useNavigate(),customer=customers.find(item=>item.id===customerId)
  const related=useMemo(()=>bookings.filter(booking=>booking.customerId===customerId).sort((a,b)=>b.serviceDate.localeCompare(a.serviceDate)),[bookings,customerId])
  if(!customer)return <div className="page resource-page"><button className="back-button" onClick={()=>navigate('/customers')}>‹ Back to customers</button><Empty label="customer records"/></div>
  return <div className="page resource-page customer-detail-page"><button className="back-button" onClick={()=>navigate('/customers')}>‹ Back to customers</button><PageHeader eyebrow="CUSTOMER RECORD" title={customer.name} description="Contact details and booking history."><button className="secondary-button" onClick={()=>navigate('/customers')}>All customers</button></PageHeader><section className="customer-contact-grid"><article className="panel"><span>CONTACT PERSON</span><strong>{customer.contact_person||'—'}</strong></article><article className="panel"><span>EMAIL</span><strong>{customer.email||'—'}</strong></article><article className="panel"><span>PHONE</span><strong>{customer.phone||'—'}</strong></article><article className="panel"><span>BOOKINGS</span><strong>{related.length}</strong></article></section><section className="panel customer-bookings"><header><div><p className="eyebrow">BOOKING HISTORY</p><h2>Associated bookings</h2></div><span>{related.length} records</span></header>{related.length?<div className="customer-booking-list">{related.map(booking=><button key={booking.uuid} onClick={()=>navigate(`/bookings/${encodeURIComponent(booking.id)}`)}><span><strong>{booking.id}</strong><small>{booking.date} · {booking.time}</small></span><span><strong>{booking.tour}</strong><small>{booking.ship} · {booking.guests} guests</small></span><span className={`customer-booking-status status-${booking.status.toLowerCase()}`}>{booking.status}</span><b>›</b></button>)}</div>:<Empty label="bookings"/>}</section></div>
}

function errorMessage(error:unknown){return error instanceof Error?error.message:'Something went wrong. Please try again.'}
